### ISSUE TITLE
:new exists

### ISSUE THREAD

**Issue by tux314159** [wangy412/nvim-scratchpad#1]

**Comment by popkat412** [comment]
`:new` doesn't actually make a file unless you save it, at which point you have to decide where to save and what to call it, and also remember to remove it later. The reason I want to have an actual file on the filesystem and also just have the filetype set correctly in general is that tools such as syntax highlighting and autocomplete work, which is the whole reason I made this in the first place

**Comment by tux314159** [comment]
Ohhh I just realised even if you set ft=... coc doesn't work XD ok thanks for letting me discover this

**Comment by AJR07** [comment]
hallo this is a very useful comment in this issue

**Comment by tux314159** [comment]
hallo ajr we are all being very productive here :)

**Comment by AJR07** [comment]
project work is killing me

**Comment by tux314159** [comment]
ehe GI "bottled vs tap???"

**Comment by tux314159** [comment]
also screw geog

**Comment by tux314159** [comment]
Geog is trash

**Comment by AJR07** [comment]
bruh

**Comment by AJR07** [comment]
physical Geog is good

**Comment by AJR07** [comment]
GI is human Geog its bad

**Comment by tux314159** [comment]
hmmmm
to be fair physical geog is mildly interesting
but History is still better :)))

**Comment by popkat412** [comment]
Why is there suddenly a discussion about geog in this thread lmao, since nothing productive is happening i'll just close it.

**Comment by tux314159** [comment]
hey!!! how could you call this unproductive!!! we are being super duper productive here!!!!!!

**Comment by AJR07** [comment]
ah yes

**Comment by tux314159** [comment]
yunze being professional...

**Comment by AJR07** [comment]
that's what ur supposed to do what

**Comment by tux314159** [comment]
Hmmm
I Wonder
Professional AJR? 😳

**Comment by AJR07** [comment]
Professional Tux? Clarifying about the issue even after its closed?

**Comment by tux314159** [comment]
COI time!!!!!!!

**Comment by tux314159** [comment]
ono AJR doesn't like philo? GASPPPPP

**Comment by AJR07** [comment]
Not doesn't like, more like not interested

**Comment by tux314159** [comment]
Ehh logic is nice tho

**Comment by tux314159** [comment]
@wangy412
